# Generated by Django 3.1.4 on 2020-12-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursery',
            old_name='name',
            new_name='nursery_name',
        ),
    ]
